name: brainstorming
description: Facilitate interactive brainstorming sessions
instructions: brainstorming.md
template: ''
author: assist
config_source: assist/config_source.json
output_folder: '{config_source}:output_folder'
communication_language: '{config_source}:communication_language'
document_output_language: '{config_source}:document_output_language'
user_name: '{config_source}:user_name'
date: system-generated
default_output_file: '{output_folder}/planning-artifacts/analysis/brainstorming-session-{{date}}.md'
standalone: true
