name: quick-spec
description: Conversational spec
instructions: quick-spec.md
template: ''
author: assist
config_source: assist/config_source.json
planning_artifacts: '{config_source}:planning_artifacts'
communication_language: '{config_source}:communication_language'
date: system-generated
default_output_file: '{planning_artifacts}/quick-spec-{{date}}.md'
standalone: true
