name: retrospective
description: Epic retrospective
instructions: retrospective.md
template: ''
author: assist
config_source: assist/config_source.json
implementation_artifacts: '{config_source}:implementation_artifacts'
communication_language: '{config_source}:communication_language'
date: system-generated
default_output_file: '{implementation_artifacts}/retrospective-{{date}}.md'
standalone: true
