name: test-story
description: Test/validate story
instructions: test-story.md
template: ''
author: assist
config_source: assist/config_source.json
implementation_artifacts: '{config_source}:implementation_artifacts'
planning_artifacts: '{config_source}:planning_artifacts'
communication_language: '{config_source}:communication_language'
date: system-generated
checklist: '{installed_path}/checklist.md'
test_report: '{implementation_artifacts}/test-reports/test-story-{{date}}.md'
standalone: true
